%% Initializing Config with physical parameters 
config = gpe.Config(struct('T', 40*10^(-9),... % the amount of condensted particles
                           'ChE', 'Rb87', ... % chemical element: Rb87/Na23
                           'gamma', 0.03, ... % dissipation parameters
                           'N', 25000));%, ...    

%% Initializing 3D coordinate grid
grid = gpe.Grid(struct('GPU', 1, ...
                       'N', 256,...
                       'Nz', 32, ...
                       'L', 120*10^(-6),...
                       'Lz', 30*10^(-6)));

%% Initializing Model
model = gpe.Model(struct('grid', grid, ...
                          'config', config));
          

model.addPotentialToroidal(struct('wr', 2*pi*110, ...
                                  'wz', 2*pi*245, ...
                                  'R', 20*10^(-6)));
                              
model.addPotentialToroidal(struct('wr', 2*pi*110, ...
                                  'wz', 2*pi*245, ...
                                  'R', 45*10^(-6)));

model.addPotentialVertical(struct('w', 2*pi*2,...
                                  'U_max', 0.8*10^(-31), ...
                                  'a_max', 1*10^-6, ...
                                  't_start', 0.04, ...
                                  't_max_start', 0.06, ...
                                  't_max_end', 0.08, ...
                                  't_end', 0.1));

model.addPotentialVertical(struct('w', 0,...
                                  'n', 4, ...
                                  'U_max', 3*10^(-31), ...
                                  'a_max', 1*10^-6, ...
                                  't_start', -0.01, ...
                                  't_max_start', 0, ...
                                  't_max_end', 0.02, ...
                                  't_end', 0.03));

%% Initializing Save, all data will be saved in 'Folder'
sv = gpe.Save(struct('model', model, ...
                        'Folder', 'example'));
                 
%% Initializing run with ITP, ZNG, GPE, SPGE methods
run = gpe.Run(struct('model', model));




                   

