%% Initializing Config with physical parameters 
config = gpe.Config(struct('T', 40*10^(-9),... % the amount of condensted particles
                           'ChE', 'Rb87', ... % chemical element: Rb87/Na23
                           'gamma', 0.03, ... % dissipation parameters
                           'N', 25000));%, ...    

%% Initializing 3D coordinate grid
grid = gpe.Grid(struct('GPU', 1, ...
                       'N', 128,...
                       'Nz', 64, ...
                       'L', 120*10^(-6),...
                       'Lz', 60*10^(-6)));

%% Initializing Model
model = gpe.Model(struct('grid', grid, ...
                          'config', config));
          

model.addPotentialToroidal(struct('wr', 2*pi*110, ...
                                  'wz', 2*pi*245, ...
                                  'R', 20*10^(-6)));
                              
model.addPotentialToroidal(struct('wr', 2*pi*110, ...
                                  'wz', 2*pi*245, ...
                                  'R', 45*10^(-6)));

model.addPotentialVertical(struct('w', 2*pi*2,...
                                  'U_max', 5*2*pi*123*1.054*10^(-34), ...
                                  'a_max', 1*10^-6))

%% Initializing Save, all data will be saved in 'Folder'
save = gpe.Save(struct('model', model, ...
                        'Folder', ['example/2pi_', ...
                                   num2str(model.Vbs(1).w/(2*pi), '%.2f')]));
                 
%% Initializing run with ITP, ZNG, GPE, SPGE methods
run = gpe.Run(struct('model', model));
[Psi, mu] = run.getITP();



                   

